# Generated by Django 4.2.6 on 2023-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(null=True, upload_to='media/music'),
        ),
    ]
